export const textStyles = {
  H1: {
    color: '#1F2124',
    fontFamily: 'NeueHaas',
    fontSize: '34px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '130%',
  },
  H1Alt: {
    color: '#1F2124',
    fontFamily: 'NeueHaas',
    fontSize: '28px',
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: '130%',
  },
  H2: {
    color: '#1F2124',
    fontFamily: 'NeueHaas',
    fontSize: '28px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '130%',
  },
  H3: {
    color: '#1F2124',
    fontFamily: 'NeueHaas',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '100%',
  },
  H4: {
    color: '#1F2124',
    fontFamily: 'NeueHaas',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '100%',
  },
  H5: {
    color: '#1F2124',
    fontFamily: 'NeueHaas',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '24px',
  },
  H6: {
    color: '#1F2124',
    fontFamily: 'NeueHaas',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: '24px',
  },
  H7: {
    color: '#1F2124',
    fontFamily: 'NeueHaas',
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: '20px',
  },
  H8: {
    color: '#1F2124',
    fontFamily: 'NeueHaas',
    fontSize: '10px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: '10px',
  },
  H9: {
    color: '#1F2124',
    fontFamily: 'NeueHaas',
    fontSize: '10px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: '15px',
  },
  Body: {
    color: '#8C98B1',
    fontFamily: 'NeueHaas',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: '130%',
  },
  Caption: {
    color: '#8C98B1',
    fontFamily: 'NeueHaas',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: '130%',
  },
  NavLink: {
    color: '#8C98B1',
    fontFamily: 'NeueHaas',
    fontSize: '10px',
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: '15px',
  },
  Pill: {
    fontSize: '10px',
    lineHeight: '1',
    fontWeight: '400',
  },
};
